### ISSUE TITLE
Move to spec

### ISSUE THREAD

**Issue by v0dro** [pgtgrly/GRruby-extension#1]
We use rspec for all our projects so this project should also use the same. Make a spec/ directory (rename test -> spec) and create an rspec structure on these lines : https://github.com/SciRuby/daru/tree/master/spec

Basically use a `spec_helper.rb` for all external requires and specific files (`*_spec.rb`) grouped by feature.

**Comment by pgtgrly** [comment]
I moved from TestUnit to RSpec in the commit [here](https://github.com/pgtgrly/GRruby-extension/commit/31908d6c3749f2784ea8218a03013551b5777d14l) and integrated it with autotest. However, now autotest is not executing code everytime a .c file is saved. Will look into it.

**Comment by v0dro** [comment]
You're using this thing? : https://github.com/autotest/autotest
