### ISSUE TITLE
Task design

### ISSUE THREAD

**Issue by v0dro** [pgtgrly/GRruby-extension#7]
When I said 'each task should be a class' I did not mean 'each kind of plot should be a task'. Also, I did not expect you to _hardcode_ values into the bar chart creator. Explain [this](https://github.com/pgtgrly/GRruby-extension/blob/GRPlot/lib/grruby/tasks/barfunctionclasses.rb#L33)?

I mean that each task in GR plot should be a separate class and calling artist methods should add certain tasks (aka classes) to the list.

So for example, `GR.setviewport` should be _its own class_ like this:
``` ruby
module Tasks
  class SetViewPort
    def initialize(args, for, this, method)
      # save args in instance vars
    end
    
    def call
       GR.setviewport(@args, @for, @this, @method)
    end
  end
end
```

And then calling a method called `foo` inside `ArtistPicasso` should be like this:
``` ruby
class ArtistPicasso
  def foo
    @tasks << Tasks::SetViewPort.new(some, args)
  end
  
  def write
    @tasks.each { |t| t.call }
  end
end
```

**Comment by mohawkjohn** [comment]
I can see arguments for hardcoding a viewport. It's not going to vary plot to plot, is it?

**Comment by v0dro** [comment]
@mohawkjohn all the functions below it are also hardcoded. Also, the hardcoded values should be properly factored into a class level constant or something like that. The current implementation is too hack-y.
